### ISSUE TITLE
Incorrect Position and Duplicate inputs

### ISSUE THREAD

**Issue by ndcunningham** [ng2-ui/ng2-auto-complete#68] opened 2016-12-06 05:57 UTC
Before Focus: 
![image](https://cloud.githubusercontent.com/assets/338948/20914440/a57df244-bb4d-11e6-86f2-5ab7cf5214ff.png)

After:
![image](https://cloud.githubusercontent.com/assets/338948/20914368/2e126b22-bb4d-11e6-817f-0b593de56989.png)

As you can see the 500 in the first image is covered by a mysterious element. The template has multiple Inputs which might be the culprit
![image](https://cloud.githubusercontent.com/assets/338948/20914538/4e6eac7c-bb4e-11e6-85f5-0f8f54b28a0f.png)

`<md-Input>` is the original input can we not just create the dropdown _only_ adopting the **source's** (Original Input) basic properties: ex. width. Instead of create our own Input?

Maybe some discussion on this?

**Comment by allenhwkim** [comment] 2016-12-06 14:48
This is by design.

1. To go back to original value, 

Assuming you enter 'garbage data' for auto complete, then press 'ESC' to cancel auto completion, we need to put the original value back.

2. To be used anywhere not only by input tag, but also in multiple auto complete, text area, or any.

   e.g. http://rawgit.com/allenhwkim/angularjs-autocomplete/master/test/autocomplete.multi.html

**Comment by ndcunningham** [comment] 2016-12-06 15:20
I think to go back to the original value we could always have the _original_ saved when the autocomplete is opened and if `ESC` is pressed set it back and close the autocomplete.

If this is the intended design then as you said just update the css.

**Comment by allenhwkim** [comment] 2016-12-10 11:10
Closing

**Closed by allenhwkim** 2016-12-10 11:10 UTC
Labels: enhancement, help wanted
