### ISSUE TITLE
How to use with reactive forms?

### ISSUE THREAD

**Issue by usmanwalana** [ng2-ui/ng2-auto-complete#62] opened 2016-11-24 13:52 UTC
I have a complex form where i want to use `ng2-auto-complete` at three different places. Currently i am using simple html select to display the list. I am using angular 2 model driven forms to handle the form. I want to replace the select list with `ng2-auto-complete` using model driven approach. Is it possible to do so or do i have to change the whole form into template driven approach?

**Comment by allenhwkim** [comment] 2016-12-01 20:11
this module can handle model-drive form well except with formGroup.

**Comment by allenhwkim** [comment] 2016-12-05 16:59
Closing. there is example on README.md using FormGroup.
Please re-open this if the issue is still not resolved.

**Closed by allenhwkim** 2016-12-05 16:59 UTC
Labels: Clarification Required.
