### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by fayvlad** [ng2-ui/ng2-auto-complete#27] opened 2016-09-27 15:23 UTC
In case when from autocomplete i've received empty array and press "enter" button - i've got error in console "Cannot property name of undefined".
I think that this bug [there](https://github.com/ng2-ui/ng2-auto-complete/blob/master/src/auto-complete.component.ts#L220) https://gyazo.com/b10c25c6598cbceb989d7a71a8a38ca7

**Comment by allenhwkim** [comment] 2016-09-27 16:00
@boban984 can you look into this issue?

**Comment by fayvlad** [comment] 2016-09-27 16:24
sorry, my node-modules version is 0.4.2, may be it is my pc can't update the version.
Pls, only check it in your version, according to code it is fixed.

**Comment by boban984** [comment] 2016-09-27 19:05
@fayvlad i will take a look, it would help if you can tell me how you set the source, are you using observable like the response from http call?

**Comment by allenhwkim** [comment] 2016-10-02 02:02
Could not reproduce this issue with new release 0.7.0. Please verify the change and close it.

**Closed** 2016-10-14 10:39 UTC
