### ISSUE TITLE
Maximum limit set 15

### ISSUE THREAD

**Issue by aminsmartsense** [ng2-ui/ng2-auto-complete#165] opened 2017-03-09 11:36 UTC
Hello,

I want to set limit of search result minimum 1 and maximum 15 but can't set maximum value more than 10. 

Please help me @allenhwkim .

Thank you.

**Comment by allenhwkim** [comment] 2017-03-09 14:40
Have you tried `max-num-list` ?

![image](https://cloud.githubusercontent.com/assets/1437734/23754829/685e8790-04ac-11e7-8b54-7a3ad8896518.png)

**Comment by danny90** [comment] 2017-03-10 04:53
Hi,

I noticed that if I set **_max-num-list_** to 3, it shows only 3 items and others cannot be seen. For me it would be preferable to show all but restrict the size of dropdown, so that, if all items cannot fit the dropdown screen, scrollbar appears.

**Comment by aminsmartsense** [comment] 2017-03-10 07:04
@allenhwkim Yes. I have try. max-num-list="25" but doesn't working.

**Comment by allenhwkim** [comment] 2017-03-14 16:15
@aminsmartsense 
I could not reproduce your issue for both local source and remote source.
There is no limit set to display number of items to `10`

http://plnkr.co/edit/eDPHjI?p=preview

My guess is your server-side API call is limiting the number of items to 10.

Closing until you provide your a plunker example.

**Closed by allenhwkim** 2017-03-14 16:15 UTC
